// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmqohiympclzvdddtqsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtcW9oaXltcGNsenZkZGR0cXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NjQwNjksImV4cCI6MjA3MjI0MDA2OX0.xMwkSOVrxbjZhU5BgvRmkFagtoBFy0na-WLKL_e5Sq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});